### PR TITLE
Add Ruby 3.2 to CI

### PR DESCRIPTION
**Pull request by dipth**

### CODE REVIEW

**Comment by dipth** [comment]
It appears that I need to rerun the CLA workflow, but it doesn't appear that I have any way to do so...

**Comment by swalkinshaw** [comment]
@dipth done. Looks like there's a legit failure on 3.2 due to the usage of refinements.

**Comment by dipth** [comment]
I would personally lean towards bumping the `graphql` dependency, but it's your call 🙂

**Comment by swalkinshaw** [comment]
Yeah I'm good with that. Would be interested in doing that?

**Comment by dipth** [comment]
Closed in favor of:
https://github.com/Shopify/graphql-batch/pull/156

**Pull request closed without merging**
